import { getTranslations } from 'next-intl/server'

export type ErrorKey =
  | 'unauthorized'
  | 'emailExists'
  | 'codeExists'
  | 'emailOrCodeExists'
  | 'validationFailed'
  | 'invalidInput'
  | 'invalidRequest'
  | 'employeeNotFound'
  | 'employeeRecordNotFound'
  | 'startDatePast'
  | 'endDateBeforeStart'
  | 'durationExceeds365'
  | 'noWorkingDays'
  | 'halfDayMustBeSingleDay'
  | 'invalidLeaveType'
  | 'sickRequiresAttachment'
  | 'overlappingRequest'
  | 'invalidAttachment'
  | 'requestNotFoundOrProcessed'
  | 'insufficientBalance'
  | 'rejectReasonRequired'
  | 'requestNotFound'
  | 'requestAlreadyCancelled'
  | 'cannotCancelProcessed'
  | 'invalidAllocation'
  | 'alreadyCheckedIn'
  | 'checkInFuture'
  | 'notCheckedIn'
  | 'alreadyCheckedOut'
  | 'invalidMonthYear'
  | 'periodExists'
  | 'noActiveEmployees'
  | 'periodNotFoundOrFinalized'
  | 'invalidDeduction'
  | 'cannotModifyFinalized'
  | 'deductionExceedsSalary'
  | 'reviewExists'
  | 'reviewNotFound'
  | 'fileRequired'
  | 'invalidDocumentFile'
  | 'documentNotFound'
  | 'taskNotFound'
  | 'taskAlreadyCompleted'
  | 'notYourTask'
  | 'assignmentNotFound'
  | 'notYourSurvey'
  | 'alreadyCompleted'

export async function serverError(key: ErrorKey): Promise<string> {
  const t = await getTranslations('errors')
  return t(key)
}
