services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: riman
      POSTGRES_PASSWORD: riman_dev
      POSTGRES_DB: riman_hr
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
